POST http://localhost:3000/create

{
    "name" : "Felipe",
    "email": "felipe@email.com",
    "password": "12345678"
}



### 
POST http://localhost:3000/login

{
    "email": "felipe@email.com",
    "password": "12345678"
}


### 
POST http://localhost:3000/repo
Authorization: Bearer TOKEN

{
    "title": "Adamas",
    "description": "uma rede social para projetos"
}


### 

GET  http://localhost:3000/search/Adamas































# ###
# POST http://localhost:3000/login

# {
#     "email": "felipe@email.com",
#     "password": "12345679"
# }

# ###
# POST http://localhost:3000/repo
# Authorization: Bearer 

# {
#     "title": "Adamas",
#     "description": "uma rede social para projetos"
# }

# ###
# GET http://localhost:3000/search/