POST http://localhost:3000/create

{
    "name" : "Felipe",
    "email": "felipe@email.com",
    "password": "12345678"
}

### 
POST http://localhost:3000/login

{
    "email": "felipe@email.com",
    "password": "12345678"
}

### 
POST http://localhost:3000/create/institution 

{
    "name" : "ETEC",
    "email": "etec@etec.com",
    "password": "12345678",
    "cnpj": 28301041000137
}

### 
POST http://localhost:3000/login/institution

{
    "email": "etec@etec.com",
    "password": "12345678"
}
### 
POST http://localhost:3000/repo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlbGlwZUBlbWFpbC5jb20iLCJleHAiOjE3MTk0MDc4MjgsImlkIjoxLCJuYW1lIjoiRmVsaXBlIiwidXNlcl90eXBlIjoiY29tbW9uX3VzZXIifQ.tzoml73Hdi-Ta-E1c2A_MF2XJtu3FwRRNgJFQMqEMuU

{
    "title": "Adamas",
    "description": "uma rede social para projetos",
    "content": "###hello world!"
}


###
PUT http://localhost:3000/repo
Authorization: Bearer TOKEN

{
    "repository_id":1,
    "description": "uma rede social para a divulgação de projetos e eventos",
    "content": "###hello world 2"
}

###
DELETE  http://localhost:3000/repo/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlbGlwZUBlbWFpbC5jb20iLCJleHAiOjE3MTk0MDg1MTgsImlkIjoxLCJuYW1lIjoiRmVsaXBlIiwidXNlcl90eXBlIjoiY29tbW9uX3VzZXIifQ.70TqU4g-Y2lPtl4NqsxIfd2G5796V57Zl_ik0O0GC1Q

{
    "email": "felipe@email.com",
    "password":"12345678"
}
###
POST  http://localhost:3000/category
Authorization: Bearer TOKEN

{
    "repository_id" : 1,
    "category_name": "agricultura"
}

###
POST http://localhost:3000/repo/1/comment
Authorization: Bearer TOKEN

{
    "comment": "muito brabo"
}

###
DELETE  http://localhost:3000/repo/1/comment
Authorization: Bearer TOKEN

{
    "comment_id" : 1
}
###
POST http://localhost:3000/event
Authorization: Bearer TOKEN

{
    "name": "Amostra de TCC",
    "address" : "ETEC ANTONIO DEVISATE, avenida castro alves",
    "date": "2020-12-02",
    "description": "Uma amostra de tcc uai"
}
### 
GET http://localhost:3000/repo
### 
GET  http://localhost:3000/repo/Adamas

###
GET http://localhost:3000/event/Amostra de TCC
