POST http://localhost:3000/create

{
    "name" : "Felipe",
    "email": "felipe@email.com",
    "password": "12345678"
}

### 
POST http://localhost:3000/login

{
    "email": "felipe@email.com",
    "password": "12345678"
}

### 
POST http://localhost:3000/create/institution 

{
    "name" : "ETEC",
    "email": "etec@etec.com",
    "password": "12345678",
    "cnpj": "28301041000137"
}

### 
POST http://localhost:3000/login/institution

{
    "email": "etec@etec.com",
    "password": "12345678"
}
### 
POST http://localhost:3000/project
Authorization: Bearer TOKEN

{
    "title": "Adamas",
    "description": "uma rede social para projetos",
    "content": "###hello world!"
}


###
PUT http://localhost:3000/project/1
Authorization: Bearer TOKEN

{
    "title": "Adamas-Projects",
    "description": "uma rede social para a divulgação de projetos e eventos",
    "content": "###hello world 2"
}

###
DELETE  http://localhost:3000/project/1
Authorization: Bearer TOKEN

{
    "email": "felipe@email.com",
    "password":"12345678"
}
###
POST  http://localhost:3000/project/1/category
Authorization: Bearer TOKEN

{
    "repository_id" : 1,
    "category_name": "ti"
}

###
POST http://localhost:3000/project/1/comment
Authorization: Bearer TOKEN

{
    "comment": "muito brabo"
}

###
DELETE  http://localhost:3000/project/1/comment
Authorization: Bearer TOKEN

{
    "comment_id" : 1
}
###
POST http://localhost:3000/event
Authorization: Bearer TOKEN

{
    "name": "Amostra de TCC",
    "address" : "ETEC ANTONIO DEVISATE, avenida castro alves",
    "date": "2020-12-02",
    "description": "Uma amostra de tcc uai"
}

###
POST http://localhost:3000/event/subscribe/1
Authorization: Bearer TOKEN

### 
GET http://localhost:3000/search/project
### 
GET  http://localhost:3000/search/project/Adamas

###
GET http://localhost:3000/search/event/Amostra de TCC
