### 
GET http://localhost:3000/project/search

### 
GET http://localhost:3000/project/search?categories=2
###
GET http://localhost:3000/project/1
### 
GET  http://localhost:3000/project/search/Adamas
###
GET http://localhost:3000/project/user/1
###
GET http://localhost:3000/event/search/Amostra de TCC

###
GET http://localhost:3000/event/search

###
GET http://localhost:3000/event/1

###
GET http://localhost:3000/event/institution/1
###
GET http://localhost:3000/event/1/approved_projects

###
GET http://localhost:3000/user/search 

###
GET http://localhost:3000/user/1
 
###
GET http://localhost:3000/user/search/Felipe 

### 
GET http://localhost:3000/institution/1